//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypingTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypingTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They improved dramatically once the lead singer left..
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today arrived with a crash of my car through the garage door..
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth in advertising and dinosaurs with skateboards have much in common..
        /// </summary>
        public static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The knives were out and she was sharpening hers..
        /// </summary>
        public static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red is greener than purple, for sure..
        /// </summary>
        public static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behind the window was a reflection that only instilled fear..
        /// </summary>
        public static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dentist tells me that chewing bricks is very bad for your teeth..
        /// </summary>
        public static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People keep telling me &quot;orange&quot; but I still prefer &quot;pink&quot;..
        /// </summary>
        public static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was an introvert that extroverts seemed to love..
        /// </summary>
        public static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peanut butter and jelly caused the elderly lady to think about her past..
        /// </summary>
        public static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His get rich quick scheme was to grow a cactus farm..
        /// </summary>
        public static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m confused: when people ask me what&apos;s up, and I point, they groan..
        /// </summary>
        public static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The toddlers endless tantrum caused the entire plane anxiety..
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She always had an interesting perspective on why the world must be flat..
        /// </summary>
        public static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluffy pink unicorns are a popular status symbol among macho men..
        /// </summary>
        public static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball..
        /// </summary>
        public static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone says they love nature until they realize how dangerous she can be..
        /// </summary>
        public static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s difficult to understand the lengths he&apos;d go to remain short..
        /// </summary>
        public static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She says she has the ability to hear the soundtrack of your life..
        /// </summary>
        public static string _115 {
            get {
                return ResourceManager.GetString("115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She wore green lipstick like a fashion icon..
        /// </summary>
        public static string _116 {
            get {
                return ResourceManager.GetString("116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like tuna and tomato sauce, try combining the two, it&apos;s really not as bad as it sounds..
        /// </summary>
        public static string _117 {
            get {
                return ResourceManager.GetString("117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I will buy the red car, or I will lease the blue one..
        /// </summary>
        public static string _118 {
            get {
                return ResourceManager.GetString("118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martha came to the conclusion that shake weights are a great gift for any occasion..
        /// </summary>
        public static string _119 {
            get {
                return ResourceManager.GetString("119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karen realized the only way she was getting into heaven was to cheat..
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager of the fruit stand always sat and only sold vegetables..
        /// </summary>
        public static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings from the real universe..
        /// </summary>
        public static string _121 {
            get {
                return ResourceManager.GetString("121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tortoise jumped into the lake with dreams of becoming a sea turtle..
        /// </summary>
        public static string _122 {
            get {
                return ResourceManager.GetString("122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He&apos;s in a boy band which doesn&apos;t make much sense for a snake..
        /// </summary>
        public static string _123 {
            get {
                return ResourceManager.GetString("123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Japanese doll..
        /// </summary>
        public static string _124 {
            get {
                return ResourceManager.GetString("124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malls are great places to shop; I can find everything I need under one roof..
        /// </summary>
        public static string _125 {
            get {
                return ResourceManager.GetString("125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He turned in the research paper on Friday; otherwise, he would have not passed the class..
        /// </summary>
        public static string _126 {
            get {
                return ResourceManager.GetString("126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Friday I saw a spotted striped blue worm shake hands with a legless lizard..
        /// </summary>
        public static string _127 {
            get {
                return ResourceManager.GetString("127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She found his complete dullness interesting..
        /// </summary>
        public static string _128 {
            get {
                return ResourceManager.GetString("128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After exploring the abandoned building, he started to believe in ghosts..
        /// </summary>
        public static string _129 {
            get {
                return ResourceManager.GetString("129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It didn&apos;t take long for Gary to detect the robbers were amateurs..
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dead duck doesn&apos;t fly backward..
        /// </summary>
        public static string _130 {
            get {
                return ResourceManager.GetString("130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blue parrot drove by the hitchhiking mongoose..
        /// </summary>
        public static string _131 {
            get {
                return ResourceManager.GetString("131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was willing to find the depths of the rabbit hole in order to be with her..
        /// </summary>
        public static string _132 {
            get {
                return ResourceManager.GetString("132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I come from a tribe of head-hunters, so I will never need a shrink..
        /// </summary>
        public static string _133 {
            get {
                return ResourceManager.GetString("133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have young kids who often walk into our room at night for various reasons including clowns in the closet..
        /// </summary>
        public static string _134 {
            get {
                return ResourceManager.GetString("134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shark-infested South Pine channel was the only way in or out..
        /// </summary>
        public static string _135 {
            get {
                return ResourceManager.GetString("135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her daily goal was to improve on yesterday..
        /// </summary>
        public static string _136 {
            get {
                return ResourceManager.GetString("136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In hopes of finding out the truth, he entered the one-room library..
        /// </summary>
        public static string _137 {
            get {
                return ResourceManager.GetString("137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People generally approve of dogs eating cat food but not cats eating dog food..
        /// </summary>
        public static string _138 {
            get {
                return ResourceManager.GetString("138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He went back to the video to see what had been recorded and was shocked at what he saw..
        /// </summary>
        public static string _139 {
            get {
                return ResourceManager.GetString("139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It didn&apos;t make sense unless you had the power to eat colors..
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tart lemonade quenched her thirst, but not her longing..
        /// </summary>
        public static string _140 {
            get {
                return ResourceManager.GetString("140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang on, my kittens are scratching at the bathtub and they&apos;ll upset by the lack of biscuits..
        /// </summary>
        public static string _141 {
            get {
                return ResourceManager.GetString("141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan ate the clouds like cotton candy..
        /// </summary>
        public static string _142 {
            get {
                return ResourceManager.GetString("142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolores wouldn&apos;t have eaten the meal if she had known what it actually was..
        /// </summary>
        public static string _143 {
            get {
                return ResourceManager.GetString("143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gruff old man sat in the back of the bait shop grumbling to himself as he scooped out a handful of worms..
        /// </summary>
        public static string _144 {
            get {
                return ResourceManager.GetString("144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She let the balloon float up into the air with her hopes and dreams..
        /// </summary>
        public static string _145 {
            get {
                return ResourceManager.GetString("145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boulders lined the side of the road foretelling what could come next..
        /// </summary>
        public static string _146 {
            get {
                return ResourceManager.GetString("146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He is no James Bond; his name is Roger Moore..
        /// </summary>
        public static string _147 {
            get {
                return ResourceManager.GetString("147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Guinea fowl flies through the air with all the grace of a turtle..
        /// </summary>
        public static string _148 {
            get {
                return ResourceManager.GetString("148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the rental car rolled to a stop on the dark road, her fear increased by the moment..
        /// </summary>
        public static string _149 {
            get {
                return ResourceManager.GetString("149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He would only survive if he kept the fire going and he could hear thunder in the distance..
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The busker hoped that the people passing by would throw money, but they threw tomatoes instead, so he exchanged his hat for a juicer..
        /// </summary>
        public static string _150 {
            get {
                return ResourceManager.GetString("150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She couldn&apos;t decide of the glass was half empty or half full so she drank it..
        /// </summary>
        public static string _151 {
            get {
                return ResourceManager.GetString("151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If any cop asks you where you were, just say you were visiting Kansas..
        /// </summary>
        public static string _152 {
            get {
                return ResourceManager.GetString("152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He colored deep space a soft yellow..
        /// </summary>
        public static string _153 {
            get {
                return ResourceManager.GetString("153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red is greener than purple, for sure..
        /// </summary>
        public static string _154 {
            get {
                return ResourceManager.GetString("154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It took him a month to finish the meal..
        /// </summary>
        public static string _155 {
            get {
                return ResourceManager.GetString("155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More RVs were seen in the storage lot than at the campground..
        /// </summary>
        public static string _156 {
            get {
                return ResourceManager.GetString("156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nancy decided to make the porta-potty her home..
        /// </summary>
        public static string _157 {
            get {
                return ResourceManager.GetString("157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He took one look at what was under the table and noped the hell out of there..
        /// </summary>
        public static string _158 {
            get {
                return ResourceManager.GetString("158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hummingbird&apos;s wings blurred while it eagerly sipped the sugar water from the feeder..
        /// </summary>
        public static string _159 {
            get {
                return ResourceManager.GetString("159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dentist tells me that chewing bricks is very bad for your teeth..
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m working on a sweet potato farm..
        /// </summary>
        public static string _160 {
            get {
                return ResourceManager.GetString("160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siri became confused when we reused to follow her directions..
        /// </summary>
        public static string _161 {
            get {
                return ResourceManager.GetString("161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whenever he saw a red flag warning at the beach he grabbed his surfboard..
        /// </summary>
        public static string _162 {
            get {
                return ResourceManager.GetString("162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Japanese yen for commerce is still well-known..
        /// </summary>
        public static string _163 {
            get {
                return ResourceManager.GetString("163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was the best sandcastle he had ever seen..
        /// </summary>
        public static string _164 {
            get {
                return ResourceManager.GetString("164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She found it strange that people use their cellphones to actually talk to one another..
        /// </summary>
        public static string _165 {
            get {
                return ResourceManager.GetString("165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom got a small piece of pie..
        /// </summary>
        public static string _166 {
            get {
                return ResourceManager.GetString("166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My dentist tells me that chewing bricks is very bad for your teeth..
        /// </summary>
        public static string _167 {
            get {
                return ResourceManager.GetString("167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At that moment he wasn&apos;t listening to music, he was living an experience..
        /// </summary>
        public static string _168 {
            get {
                return ResourceManager.GetString("168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a growing trend among teenagers of using frisbees as go-cart wheels..
        /// </summary>
        public static string _169 {
            get {
                return ResourceManager.GetString("169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans for this weekend include turning wine into water..
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He never understood why what, when, and where left out who..
        /// </summary>
        public static string _170 {
            get {
                return ResourceManager.GetString("170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her life in the confines of the house became her new normal..
        /// </summary>
        public static string _171 {
            get {
                return ResourceManager.GetString("171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She moved forward only because she trusted that the ending she now was going through must be followed by a new beginning..
        /// </summary>
        public static string _172 {
            get {
                return ResourceManager.GetString("172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sudden rainstorm washed crocodiles into the ocean..
        /// </summary>
        public static string _173 {
            get {
                return ResourceManager.GetString("173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She hadn&apos;t had her cup of coffee, and that made things all the worse..
        /// </summary>
        public static string _174 {
            get {
                return ResourceManager.GetString("174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash photography is best used in full sunlight..
        /// </summary>
        public static string _175 {
            get {
                return ResourceManager.GetString("175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At last there was a moving rabbit in front of me..
        /// </summary>
        public static string _176 {
            get {
                return ResourceManager.GetString("176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A kangaroo is really just a rabbit on steroids..
        /// </summary>
        public static string _177 {
            get {
                return ResourceManager.GetString("177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock music approaches at high velocity..
        /// </summary>
        public static string _178 {
            get {
                return ResourceManager.GetString("178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When motorists sped in and out of traffic, all she could think of was those in need of a transplant..
        /// </summary>
        public static string _179 {
            get {
                return ResourceManager.GetString("179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I honestly find her about as intimidating as a basket of kittens..
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no better feeling than staring at a wall with closed eyes..
        /// </summary>
        public static string _180 {
            get {
                return ResourceManager.GetString("180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am my aunt&apos;s sister&apos;s daughter..
        /// </summary>
        public static string _181 {
            get {
                return ResourceManager.GetString("181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He wasn&apos;t bitter that she had moved on but from the radish..
        /// </summary>
        public static string _182 {
            get {
                return ResourceManager.GetString("182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm beer on a cold day isn&apos;t my idea of fun..
        /// </summary>
        public static string _183 {
            get {
                return ResourceManager.GetString("183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She cried diamonds..
        /// </summary>
        public static string _184 {
            get {
                return ResourceManager.GetString("184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some unfathomable reason, the response team didn&apos;t consider a lack of milk for my cereal as a proper emergency..
        /// </summary>
        public static string _185 {
            get {
                return ResourceManager.GetString("185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d rather be a bird than a fish..
        /// </summary>
        public static string _186 {
            get {
                return ResourceManager.GetString("186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flesh-colored yoga pants were far worse than even he feared..
        /// </summary>
        public static string _187 {
            get {
                return ResourceManager.GetString("187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t sound like that will ever be on my travel list..
        /// </summary>
        public static string _188 {
            get {
                return ResourceManager.GetString("188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fog was so dense even a laser decided it wasn&apos;t worth the effort..
        /// </summary>
        public static string _189 {
            get {
                return ResourceManager.GetString("189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He had unknowingly taken up sleepwalking as a nighttime hobby..
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When she didn&apos;t like a guy who was trying to pick her up, she started using sign language..
        /// </summary>
        public static string _190 {
            get {
                return ResourceManager.GetString("190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happiness can be found in the depths of chocolate pudding..
        /// </summary>
        public static string _191 {
            get {
                return ResourceManager.GetString("191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr. Montoya knows the way to the bakery even though he&apos;s never been there..
        /// </summary>
        public static string _192 {
            get {
                return ResourceManager.GetString("192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The light that burns twice as bright burns half as long..
        /// </summary>
        public static string _193 {
            get {
                return ResourceManager.GetString("193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He stepped gingerly onto the bridge knowing that enchantment awaited on the other side..
        /// </summary>
        public static string _194 {
            get {
                return ResourceManager.GetString("194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just because the water is red doesn&apos;t mean you can&apos;t drink it..
        /// </summary>
        public static string _195 {
            get {
                return ResourceManager.GetString("195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can never be too many cherries on an ice cream sundae..
        /// </summary>
        public static string _196 {
            get {
                return ResourceManager.GetString("196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My biggest joy is roasting almonds while stalking prey..
        /// </summary>
        public static string _197 {
            get {
                return ResourceManager.GetString("197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s important to remember to be aware of rampaging grizzly bears..
        /// </summary>
        public static string _198 {
            get {
                return ResourceManager.GetString("198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are few things better in life than a slice of pie..
        /// </summary>
        public static string _199 {
            get {
                return ResourceManager.GetString("199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not a party animal, but I do like animal parties..
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re careful about orange ping pong balls because people might think they&apos;re fruit..
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He said he was not there yesterday; however, many people saw him there..
        /// </summary>
        public static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarah ran from the serial killer holding a jug of milk..
        /// </summary>
        public static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm beer on a cold day isn&apos;t my idea of fun..
        /// </summary>
        public static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing on one&apos;s head at job interviews forms a lasting impression..
        /// </summary>
        public static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dead trees waited to be ignited by the smallest spark and seek their revenge..
        /// </summary>
        public static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you spin around three times, you&apos;ll start to feel melancholy..
        /// </summary>
        public static string _205 {
            get {
                return ResourceManager.GetString("205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He decided to live his life by the big beats manifesto..
        /// </summary>
        public static string _206 {
            get {
                return ResourceManager.GetString("206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A suit of armor provides excellent sun protection on hot days..
        /// </summary>
        public static string _207 {
            get {
                return ResourceManager.GetString("207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shakespeare was a famous 17th-century diesel mechanic..
        /// </summary>
        public static string _208 {
            get {
                return ResourceManager.GetString("208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I made myself a peanut butter sandwich as I didn&apos;t want to subsist on veggie crackers..
        /// </summary>
        public static string _209 {
            get {
                return ResourceManager.GetString("209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He said he was not there yesterday; however, many people saw him there..
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joe made the sugar cookies; Susan decorated them..
        /// </summary>
        public static string _210 {
            get {
                return ResourceManager.GetString("210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It didn&apos;t take long for Gary to detect the robbers were amateurs..
        /// </summary>
        public static string _211 {
            get {
                return ResourceManager.GetString("211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He decided to fake his disappearance to avoid jail..
        /// </summary>
        public static string _212 {
            get {
                return ResourceManager.GetString("212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stench from the feedlot permeated the car despite having the air conditioning on recycled air..
        /// </summary>
        public static string _213 {
            get {
                return ResourceManager.GetString("213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like tuna and tomato sauce, try combining the two, it&apos;s really not as bad as it sounds..
        /// </summary>
        public static string _214 {
            get {
                return ResourceManager.GetString("214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underground bunker was filled with chips and candy..
        /// </summary>
        public static string _215 {
            get {
                return ResourceManager.GetString("215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was how he came to win $1 million..
        /// </summary>
        public static string _216 {
            get {
                return ResourceManager.GetString("216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two seats were vacant..
        /// </summary>
        public static string _217 {
            get {
                return ResourceManager.GetString("217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situps are a terrible way to end your day..
        /// </summary>
        public static string _218 {
            get {
                return ResourceManager.GetString("218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rusty nail stood erect, angled at a 45-degree angle, just waiting for the perfect barefoot to come along..
        /// </summary>
        public static string _219 {
            get {
                return ResourceManager.GetString("219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doris enjoyed tapping her nails on the table to annoy everyone..
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David proudly graduated from high school top of his class at age 97..
        /// </summary>
        public static string _220 {
            get {
                return ResourceManager.GetString("220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been eyeing me all day and waiting for your move like a lion stalking a gazelle in a savannah..
        /// </summary>
        public static string _221 {
            get {
                return ResourceManager.GetString("221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sight of his goatee made me want to run and hide under my sister-in-law&apos;s bed..
        /// </summary>
        public static string _222 {
            get {
                return ResourceManager.GetString("222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She insisted that cleaning out your closet was the key to good driving..
        /// </summary>
        public static string _223 {
            get {
                return ResourceManager.GetString("223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David subscribes to the &quot;stuff your tent into the bag&quot; strategy over nicely folding it..
        /// </summary>
        public static string _224 {
            get {
                return ResourceManager.GetString("224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thunderous roar of the jet overhead confirmed her worst fears..
        /// </summary>
        public static string _225 {
            get {
                return ResourceManager.GetString("225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate covered crickets were his favorite snack..
        /// </summary>
        public static string _226 {
            get {
                return ResourceManager.GetString("226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The truth is that you pay for your lifestyle in hours..
        /// </summary>
        public static string _227 {
            get {
                return ResourceManager.GetString("227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beach was crowded with snow leopards..
        /// </summary>
        public static string _228 {
            get {
                return ResourceManager.GetString("228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The random sentence generator generated a random sentence about a random sentence..
        /// </summary>
        public static string _229 {
            get {
                return ResourceManager.GetString("229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He had accidentally hacked into his company&apos;s server..
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash covered the landscape like sprinkles do a birthday cake..
        /// </summary>
        public static string _230 {
            get {
                return ResourceManager.GetString("230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He embraced his new life as an eggplant..
        /// </summary>
        public static string _231 {
            get {
                return ResourceManager.GetString("231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She folded her handkerchief neatly..
        /// </summary>
        public static string _232 {
            get {
                return ResourceManager.GetString("232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have never been to Asia, nor have we visited Africa..
        /// </summary>
        public static string _233 {
            get {
                return ResourceManager.GetString("233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anaconda was the greatest criminal mastermind in this part of the neighborhood..
        /// </summary>
        public static string _234 {
            get {
                return ResourceManager.GetString("234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nancy decided to make the porta-potty her home..
        /// </summary>
        public static string _235 {
            get {
                return ResourceManager.GetString("235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erin accidentally created a new universe..
        /// </summary>
        public static string _236 {
            get {
                return ResourceManager.GetString("236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to convince a monkey to give you a banana by promising it infinite bananas when they die..
        /// </summary>
        public static string _237 {
            get {
                return ResourceManager.GetString("237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He barked orders at his daughters but they just stared back with amusement..
        /// </summary>
        public static string _238 {
            get {
                return ResourceManager.GetString("238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When she didn&apos;t like a guy who was trying to pick her up, she started using sign language..
        /// </summary>
        public static string _239 {
            get {
                return ResourceManager.GetString("239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They say that dogs are man&apos;s best friend, but this cat was setting out to sabotage that theory..
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edith could decide if she should paint her teeth or brush her nails..
        /// </summary>
        public static string _240 {
            get {
                return ResourceManager.GetString("240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She cried diamonds..
        /// </summary>
        public static string _241 {
            get {
                return ResourceManager.GetString("241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some unfathomable reason, the response team didn&apos;t consider a lack of milk for my cereal as a proper emergency..
        /// </summary>
        public static string _242 {
            get {
                return ResourceManager.GetString("242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He kept telling himself that one day it would all somehow make sense..
        /// </summary>
        public static string _243 {
            get {
                return ResourceManager.GetString("243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock music approaches at high velocity..
        /// </summary>
        public static string _244 {
            get {
                return ResourceManager.GetString("244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It had been sixteen days since the zombies first attacked..
        /// </summary>
        public static string _245 {
            get {
                return ResourceManager.GetString("245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If eating three-egg omelets causes weight-gain, budgie eggs are a good substitute..
        /// </summary>
        public static string _246 {
            get {
                return ResourceManager.GetString("246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursive writing is the best way to build a race track..
        /// </summary>
        public static string _247 {
            get {
                return ResourceManager.GetString("247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll see the rainbow bridge after it rains cats and dogs..
        /// </summary>
        public static string _248 {
            get {
                return ResourceManager.GetString("248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malls are great places to shop; I can find everything I need under one roof..
        /// </summary>
        public static string _249 {
            get {
                return ResourceManager.GetString("249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At that moment I was the most fearsome weasel in the entire swamp..
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wooden spoon couldnt cut but left emotional scars..
        /// </summary>
        public static string _250 {
            get {
                return ResourceManager.GetString("250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no ice cream in the freezer, nor did they have money to go to the store..
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He had concluded that pigs must be able to fly in Hog Heaven..
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All you need to do is pick up the pen and begin..
        /// </summary>
        public static string _28 {
            get {
                return ResourceManager.GetString("28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strawberries must be the one food that doesn&apos;t go well with this brand of paint..
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t like toenails, you probably shouldn&apos;t look at your feet..
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She moved forward only because she trusted that the ending she now was going through must be followed by a new beginning..
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am my aunt&apos;s sister&apos;s daughter..
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green should have smelled more tranquil, but somehow it just tasted rotten..
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Great Dane looked more like a horse than a dog..
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He wore the surgical mask in public not to keep from catching a virus, but to keep people away from him..
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erin accidentally created a new universe..
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings from the real universe..
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This made him feel like an old-style rootbeer float smells..
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just wanted to tell you I could see the love you have for your child by the way you look at her..
        /// </summary>
        public static string _38 {
            get {
                return ResourceManager.GetString("38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She felt that chill that makes the hairs on the back of your neck when he walked into the room..
        /// </summary>
        public static string _39 {
            get {
                return ResourceManager.GetString("39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevin embraced his ability to be at the wrong place at the wrong time..
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mum tries to be cool by saying that she likes all the same things that I do..
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were white out conditions in the town; subsequently, the roads were impassable..
        /// </summary>
        public static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He found his art never progressed when he literally used his sweat and tears..
        /// </summary>
        public static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth in advertising and dinosaurs with skateboards have much in common..
        /// </summary>
        public static string _43 {
            get {
                return ResourceManager.GetString("43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She wondered what his eyes were saying beneath his mirrored sunglasses..
        /// </summary>
        public static string _44 {
            get {
                return ResourceManager.GetString("44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility..
        /// </summary>
        public static string _45 {
            get {
                return ResourceManager.GetString("45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek success, but always be prepared for random cats..
        /// </summary>
        public static string _46 {
            get {
                return ResourceManager.GetString("46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d always thought lightning was something only I could see..
        /// </summary>
        public static string _47 {
            get {
                return ResourceManager.GetString("47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He had a wall full of masks so she could wear a different face every day..
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the rental car rolled to a stop on the dark road, her fear increased by the moment..
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It took me too long to realize that the ceiling hadn&apos;t been painted to look like the sky..
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had he known what was going to happen, he would have never stepped into the shower..
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The efficiency with which he paired the socks in the drawer was quite admirable..
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was fishing for compliments and accidentally caught a trout..
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I met an interesting turtle while the song on the radio blasted away..
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an art to getting your way, and spitting olive pits across the table isn&apos;t it..
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joyce enjoyed eating pancakes with ketchup..
        /// </summary>
        public static string _55 {
            get {
                return ResourceManager.GetString("55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was her first experience training a rainbow unicorn..
        /// </summary>
        public static string _56 {
            get {
                return ResourceManager.GetString("56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giving directions that the mountains are to the west only works when you can see them..
        /// </summary>
        public static string _57 {
            get {
                return ResourceManager.GetString("57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despite what your teacher may have told you, there is a wrong way to wield a lasso..
        /// </summary>
        public static string _58 {
            get {
                return ResourceManager.GetString("58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings from the galaxy MACS0647-JD, or what we call home..
        /// </summary>
        public static string _59 {
            get {
                return ResourceManager.GetString("59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He swore he just saw his sushi move..
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swim at your own risk was taken as a challenge for the group of Kansas City college students..
        /// </summary>
        public static string _60 {
            get {
                return ResourceManager.GetString("60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tsunami wave crashed against the raised houses and broke the pilings as if they were toothpicks..
        /// </summary>
        public static string _61 {
            get {
                return ResourceManager.GetString("61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The teens wondered what was kept in the red shed on the far edge of the school grounds..
        /// </summary>
        public static string _62 {
            get {
                return ResourceManager.GetString("62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He&apos;s in a boy band which doesn&apos;t make much sense for a snake..
        /// </summary>
        public static string _63 {
            get {
                return ResourceManager.GetString("63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The near-death experience brought new ideas to light..
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She says she has the ability to hear the soundtrack of your life..
        /// </summary>
        public static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The green tea and avocado smoothie turned out exactly as would be expected..
        /// </summary>
        public static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malls are great places to shop; I can find everything I need under one roof..
        /// </summary>
        public static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sign said there was road work ahead so he decided to speed up..
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two seats were vacant..
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was the scarcity that fueled his creativity..
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to She hadn&apos;t had her cup of coffee, and that made things all the worse..
        /// </summary>
        public static string _70 {
            get {
                return ResourceManager.GetString("70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom got a small piece of pie..
        /// </summary>
        public static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He was sure the Devil created red sparkly glitter..
        /// </summary>
        public static string _72 {
            get {
                return ResourceManager.GetString("72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle&apos;s disappearance..
        /// </summary>
        public static string _73 {
            get {
                return ResourceManager.GetString("73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t put peanut butter on the dog&apos;s nose..
        /// </summary>
        public static string _74 {
            get {
                return ResourceManager.GetString("74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They finished building the road they knew no one would ever use..
        /// </summary>
        public static string _75 {
            get {
                return ResourceManager.GetString("75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bullet pierced the window shattering it before missing Danny&apos;s head by mere millimeters..
        /// </summary>
        public static string _76 {
            get {
                return ResourceManager.GetString("76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a message for you if you look up..
        /// </summary>
        public static string _77 {
            get {
                return ResourceManager.GetString("77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is as cautiously cuddly as a pet porcupine..
        /// </summary>
        public static string _78 {
            get {
                return ResourceManager.GetString("78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tour bus was packed with teenage girls heading toward their next adventure..
        /// </summary>
        public static string _79 {
            get {
                return ResourceManager.GetString("79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over..
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They decided to plant an orchard of cotton candy..
        /// </summary>
        public static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The murder hornet was disappointed by the preconceived ideas people had of him..
        /// </summary>
        public static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He waited for the stop sign to turn to a go sign..
        /// </summary>
        public static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boulders lined the side of the road foretelling what could come next..
        /// </summary>
        public static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stranger officiates the meal..
        /// </summary>
        public static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow will bring something new, so leave today as a memory..
        /// </summary>
        public static string _85 {
            get {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody should read Chaucer to improve their everyday vocabulary..
        /// </summary>
        public static string _86 {
            get {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolores wouldn&apos;t have eaten the meal if she had known what it actually was..
        /// </summary>
        public static string _87 {
            get {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon..
        /// </summary>
        public static string _88 {
            get {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to rent a room for our party..
        /// </summary>
        public static string _89 {
            get {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He found a leprechaun in his walnut shell..
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fish listened intently to what the frogs had to say..
        /// </summary>
        public static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For oil spots on the floor, nothing beats parking a motorbike in the lounge..
        /// </summary>
        public static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After exploring the abandoned building, he started to believe in ghosts..
        /// </summary>
        public static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll see the rainbow bridge after it rains cats and dogs..
        /// </summary>
        public static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have never been to Asia, nor have we visited Africa..
        /// </summary>
        public static string _94 {
            get {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am never at home on Sundays..
        /// </summary>
        public static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful with that butter knife..
        /// </summary>
        public static string _96 {
            get {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gary didn&apos;t understand why Doug went upstairs to get one dollar bills when he invited him to go cow tipping..
        /// </summary>
        public static string _97 {
            get {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenny made the announcement that her baby was an alien..
        /// </summary>
        public static string _98 {
            get {
                return ResourceManager.GetString("98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Great Dane looked more like a horse than a dog..
        /// </summary>
        public static string _99 {
            get {
                return ResourceManager.GetString("99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream KeyboardSoundEffect {
            get {
                return ResourceManager.GetStream("Mechanical_Keyboard_single_button_presses_10_www_FesliyanStudios_com", resourceCulture);
            }
        }
    }
}
